[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["cd astro-solar && npm ci"]

[phases.build]
cmds = ["cd astro-solar && npm run build"]

[variables]
HOST = "0.0.0.0"
PORT = "3000"

[start]
cmd = "node astro-solar/dist/server/entry.mjs"
